version: '3'

volumes:
  postgres_volume:

services:
  pg-local:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5430:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data
